# Generated by cucumber-sinatra. (2013-09-27 12:12:18 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/chitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'database_cleaner'
require 'database_cleaner/cucumber'

Capybara.app = Chitter

DatabaseCleaner.strategy = :truncation

Before do
  DatabaseCleaner.start
end

After do |scenario|
  DatabaseCleaner.clean
end

Before('@sign_in_out') do 
	User.create(:email => "test@test.com",
              :password => 'test', 
              :password_confirmation => 'test',
              :chandle => '£test',
              :name => 'Test Test')
end

class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ChitterWorld.new
end
